version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - project_template_DB__uri=postgresql://postgres:postgres@db:5432/project_template
      - project_template_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: project_template_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/project_template_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=project_template, project_template_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
